# general:
#     grab_resolution: 'HD720' # TODO: check out how to get full/higher resolution?
pos_tracking:
    pos_tracking_enabled: false
    publish_tf: false
    publish_map_tf: false
    # publish_urdf: false
    reset_odom_with_loop_closure: false
