# Automatically generated by: ros2nix --
{ lib, buildRosPackage, action-msgs, ament-cmake-auto, geometry-msgs, rosidl-default-generators, rosidl-default-runtime, sensor-msgs, std-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-interfaces";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto rosidl-default-generators ];
  propagatedBuildInputs = [ action-msgs geometry-msgs rosidl-default-runtime sensor-msgs std-msgs ];
  nativeBuildInputs = [ ament-cmake-auto rosidl-default-generators ];

  meta = {
    description = "Interfaces for all_seaing_vehicle";
    license = with lib.licenses; [ mit ];
  };
}
