#!/bin/bash
: '
Reference: https://github.com/mgonzs13/yolov8_ros

make sure to colcon build --symlink-install
source dev_ws/install/setup.bash
source vrx_ws/install/setup.bash
'

: '
Parameters to Yolov8 Launch
    model: YOLOv8 model (default: yolov8m.pt)
    tracker: tracker file (default: bytetrack.yaml)
    device: GPU/CUDA (default: cuda:0)
    enable: wether to start YOLOv8 enabled (default: True)
    threshold: detection threshold (default: 0.5)
    input_image_topic: camera topic of RGB images (default: /camera/rgb/image_raw)
    image_reliability: reliability for the image topic: 0=system default, 1=Reliable, 2=Best Effort (default: 2)
'

ros2 launch yolov8_bringup yolov8.launch.py \
    model:=../../models/****ADD YOLOV8 MODEL HERE****


