# Automatically generated by: ros2nix --
{ lib, buildRosPackage, ament-cmake-auto }:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-description";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "URDF and meshes for all_seaing_vehicle";
    license = with lib.licenses; [ mit ];
  };
}
