# Automatically generated by: ros2nix --
{
  lib,
  buildRosPackage,
  all-seaing-interfaces,
  ament-cmake-auto,
  geometry-msgs,
  nav-msgs,
  rclcpp,
  rclpy,
  sensor-msgs,
  tf2,
}:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-navigation";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [
    all-seaing-interfaces
    geometry-msgs
    nav-msgs
    rclcpp
    rclpy
    sensor-msgs
    tf2
  ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Navigation nodes for all_seaing_vehicle";
    license = with lib.licenses; [ mit ];
  };
}
