wamv_imu:
    - name: imu_wamv
      x: -0.65
      y: 0.0
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0
wamv_gps:
    - name: gps_wamv
      x: -0.65
      y: 0.0
      z: 1.3
      R: 0.0
      P: 0.0
      Y: 0.0