# Automatically generated by: ros2nix --
{ lib, buildRosPackage, all-seaing-interfaces, ament-cmake-auto, geometry-msgs, nav-msgs, rclcpp, rclpy, sensor-msgs, std-msgs, visualization-msgs }:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-utility";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [ all-seaing-interfaces geometry-msgs nav-msgs rclcpp rclpy sensor-msgs std-msgs visualization-msgs ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Utility nodes for all_seaing_vehicle";
    license = with lib.licenses; [ mit ];
  };
}
