# Automatically generated by: ros2nix --
{
  lib,
  buildRosPackage,
  all-seaing-autonomy,
  all-seaing-controller,
  all-seaing-description,
  all-seaing-driver,
  all-seaing-interfaces,
  all-seaing-navigation,
  all-seaing-perception,
  all-seaing-utility,
  ament-cmake-auto,
  robot-localization,
  rviz-satellite,
}:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-bringup";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [
    all-seaing-autonomy
    all-seaing-controller
    all-seaing-description
    all-seaing-driver
    all-seaing-interfaces
    all-seaing-navigation
    all-seaing-perception
    all-seaing-utility
    robot-localization
    rviz-satellite
  ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Launch file collection for all_seaing_vehicle";
    license = with lib.licenses; [ mit ];
  };
}
