# Automatically generated by: ros2nix --
{
  lib,
  buildRosPackage,
  all-seaing-interfaces,
  ament-cmake-auto,
  nav-msgs,
  rclcpp,
  rclpy,
}:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-autonomy";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [
    all-seaing-interfaces
    nav-msgs
    rclcpp
    rclpy
  ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Autonomy code to deploy all_seaing_vehicle in competitions";
    license = with lib.licenses; [ mit ];
  };
}
