black_buoy: 0
black_circle: 1
black_cross: 2
black_triangle: 3
blue_buoy: 4
blue_circle: 5
blue_cross: 6
blue_racquet_ball: 7
blue_triangle: 8
dock: 9
duck_image: 10
green_buoy: 11
green_circle: 12
green_cross: 13
green_pole_buoy: 14
green_triangle: 15
misc_buoy: 16
red_buoy: 17
red_circle: 18
red_cross: 19
red_pole_buoy: 20
red_racquet_ball: 21
red_square: 22
red_triangle: 23
rubber_duck: 24
yellow_buoy: 25
yellow_racquet_ball: 26