black_buoy: 0
black_circle: 1
black_cross: 2
black_triangle: 3
blue_buoy: 4
blue_circle: 5
blue_cross: 6
blue_racquet_ball: 7
blue_triangle: 8
dock: 9
green_buoy: 10
green_circle: 11
green_cross: 12
green_pole_buoy: 13
green_triangle: 14
red_buoy: 15
red_circle: 16
red_cross: 17
red_pole_buoy: 18
red_racquet_ball: 19
red_square: 20
red_triangle: 21
yellow_buoy: 22
yellow_racquet_ball: 23