black_circle: 0
black_cross: 1
black_triangle: 2
blue_circle: 3
blue_cross: 4
blue_square: 5
blue_triangle: 6
dock: 7
green_circle: 8
green_cross: 9
green_square: 10
green_triangle: 11
red_circle: 12
red_cross: 13
red_square: 14
red_triangle: 15