# Automatically generated by: ros2nix --
{
  lib,
  buildRosPackage,
  ament-cmake-auto,
  cv-bridge,
  mavros-msgs,
  rclcpp,
  rclpy,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-driver";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [
    cv-bridge
    mavros-msgs
    rclcpp
    rclpy
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Software interface for ASV hardware";
    license = with lib.licenses; [ mit ];
  };
}
