# Automatically generated by: ros2nix --
{
  lib,
  buildRosPackage,
  all-seaing-interfaces,
  ament-cmake-auto,
  cv-bridge,
  geometry-msgs,
  image-geometry,
  nav-msgs,
  pcl-ros,
  rclcpp,
  rclpy,
  sensor-msgs,
  std-msgs,
  tf2,
  tf2-ros,
  tf2-sensor-msgs,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-rolling-all-seaing-perception";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake-auto ];
  propagatedBuildInputs = [
    all-seaing-interfaces
    cv-bridge
    geometry-msgs
    image-geometry
    nav-msgs
    pcl-ros
    rclcpp
    rclpy
    sensor-msgs
    std-msgs
    tf2
    tf2-ros
    tf2-sensor-msgs
    visualization-msgs
  ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "Perception nodes for all_seaing_vehicle";
    license = with lib.licenses; [ mit ];
  };
}
